#!/bin/sh
set -eu
env_file=/opt/supabase-ccn/stack/.env
grep -E '^(SUPABASE_PUBLIC_URL|SUPABASE_PUBLISHABLE_KEY|SUPABASE_SECRET_KEY|ANON_KEY|SERVICE_ROLE_KEY|DASHBOARD_USERNAME|DASHBOARD_PASSWORD)=' "$env_file"
