create table if not exists public.faq_media (
  id bigint generated by default as identity primary key,
  faq_id bigint not null references public.faq_entries(id) on delete cascade,
  object_path text not null unique,
  alt_text text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists faq_media_faq_order_idx
on public.faq_media (faq_id, sort_order, id);

alter table public.faq_media enable row level security;
grant select on public.faq_media to anon, authenticated;
grant insert, update, delete on public.faq_media to authenticated;
grant usage, select on sequence public.faq_media_id_seq to authenticated;

create policy "Public reads media of published FAQ"
on public.faq_media for select to anon, authenticated
using (
  exists (
    select 1 from public.faq_entries
    where faq_entries.id = faq_media.faq_id
      and (faq_entries.is_published or (select public.is_admin()))
  )
);

create policy "Admins create FAQ media"
on public.faq_media for insert to authenticated
with check ((select public.is_admin()));

create policy "Admins update FAQ media"
on public.faq_media for update to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create policy "Admins delete FAQ media"
on public.faq_media for delete to authenticated
using ((select public.is_admin()));
