create extension if not exists pg_trgm;

create table if not exists public.catalog_entries (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('gu', 'killer-moves', 'equipment', 'effects', 'creatures')),
  source_id text not null,
  name text not null,
  image_path text,
  category text not null default 'Chưa phân loại',
  rank text,
  summary text not null default '',
  attributes jsonb not null default '[]'::jsonb,
  details jsonb not null default '[]'::jsonb,
  search_text text generated always as (lower(name || ' ' || source_id || ' ' || summary || ' ' || category || ' ' || coalesce(rank, ''))) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (kind, source_id)
);

create table if not exists public.gu_recipes (
  id bigint generated by default as identity primary key,
  gu_entry_id bigint not null references public.catalog_entries(id) on delete cascade,
  source_id text not null,
  name text not null,
  summary text not null default '',
  sort_order integer not null default 0,
  unique (gu_entry_id, source_id)
);

create table if not exists public.recipe_ingredients (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null references public.gu_recipes(id) on delete cascade,
  position integer not null,
  description text not null,
  unique (recipe_id, position)
);

create table if not exists public.killer_move_slots (
  id bigint generated by default as identity primary key,
  killer_move_id bigint not null references public.catalog_entries(id) on delete cascade,
  position smallint not null check (position between 1 and 11),
  item_source_id text not null,
  item_name text not null,
  unique (killer_move_id, position)
);

create table if not exists public.wiki_chapters (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  category text not null,
  description text not null default '',
  content text not null,
  chapter_index integer not null default 0,
  updated_at timestamptz not null default now()
);

create index if not exists catalog_entries_kind_category_idx on public.catalog_entries(kind, category);
create index if not exists catalog_entries_search_trgm_idx on public.catalog_entries using gin(search_text gin_trgm_ops);
create index if not exists wiki_chapters_slug_idx on public.wiki_chapters(slug);

alter table public.catalog_entries enable row level security;
alter table public.gu_recipes enable row level security;
alter table public.recipe_ingredients enable row level security;
alter table public.killer_move_slots enable row level security;
alter table public.wiki_chapters enable row level security;

grant usage on schema public to anon, authenticated, service_role;
grant select on public.catalog_entries, public.gu_recipes, public.recipe_ingredients, public.killer_move_slots, public.wiki_chapters to anon, authenticated;
grant all privileges on public.catalog_entries, public.gu_recipes, public.recipe_ingredients, public.killer_move_slots, public.wiki_chapters to service_role;
grant usage, select on all sequences in schema public to service_role;

create policy "Public catalog is readable" on public.catalog_entries for select to anon, authenticated using (true);
create policy "Public recipes are readable" on public.gu_recipes for select to anon, authenticated using (true);
create policy "Public ingredients are readable" on public.recipe_ingredients for select to anon, authenticated using (true);
create policy "Public killer move slots are readable" on public.killer_move_slots for select to anon, authenticated using (true);
create policy "Public wiki is readable" on public.wiki_chapters for select to anon, authenticated using (true);

create or replace function public.set_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists catalog_entries_updated_at on public.catalog_entries;
create trigger catalog_entries_updated_at before update on public.catalog_entries for each row execute function public.set_updated_at();

drop trigger if exists wiki_chapters_updated_at on public.wiki_chapters;
create trigger wiki_chapters_updated_at before update on public.wiki_chapters for each row execute function public.set_updated_at();
