create table if not exists public.faq_entries (
  id bigint generated by default as identity primary key,
  question text not null check (length(trim(question)) > 0),
  answer text not null check (length(trim(answer)) > 0),
  category text not null default 'Chung',
  sort_order integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.faq_entries enable row level security;
grant select on public.faq_entries to anon, authenticated;
grant insert, update, delete on public.faq_entries to authenticated;
grant usage, select on sequence public.faq_entries_id_seq to authenticated;

create policy "Public reads published FAQ"
on public.faq_entries for select to anon, authenticated
using (is_published or (select public.is_admin()));

create policy "Admins create FAQ"
on public.faq_entries for insert to authenticated
with check ((select public.is_admin()));

create policy "Admins update FAQ"
on public.faq_entries for update to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create policy "Admins delete FAQ"
on public.faq_entries for delete to authenticated
using ((select public.is_admin()));

create or replace function public.set_faq_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger faq_entries_set_updated_at
before update on public.faq_entries
for each row execute function public.set_faq_updated_at();

insert into public.faq_entries (question, answer, category, sort_order) values
('Tham ngộ Tâm đắc, Tàn phương và Sát chiêu như thế nào?', '- Tham ngộ **Lưu phái Tâm đắc** tốn Niệm đầu; loại Phổ thông không cần cảnh giới, loại Chuẩn Đại sư/Đại sư/Chuẩn Tông sư cần cảnh giới lưu phái tương ứng.\n- **Cổ trùng Tàn phương** cần cảnh giới Luyện đạo: tứ chuyển cần Chuẩn Đại sư, ngũ chuyển cần Đại sư.\n- **Tàn phá Sát chiêu**: tam chuyển cần EXP lưu phái ≥ 50; tứ chuyển ≥ 100; ngũ chuyển ≥ 500.\n- Nhấp phải vật phẩm để mở GUI tham ngộ; độ bền là tiến độ. Nhấp các Niệm đầu nổi lên để tăng tiến độ.', 'Tham ngộ', 10),
('Làm sao thăng cấp cảnh giới lưu phái và tăng Nhân khí?', '- Dùng Cổ trùng, Sát chiêu hoặc Tâm đắc **cùng chuyển và cùng lưu phái** để tăng độ thuần thục.\n- **Nhân khí là tổng độ thuần thục của mọi lưu phái**, giúp tăng tỉ lệ đột phá.\n- Khi tăng giới hạn máu hoặc Hồn phách, Nhân khí nhận được bằng 1/10 giá trị tăng.', 'Tu hành', 20),
('Cho Cổ ăn và luyện hóa Cổ như thế nào?', 'Đặt thức ăn ở **tay phụ**, Cổ ở **tay chính**, rồi nhấp chuột phải. Một số Cổ yêu cầu ngồi xổm + chuột phải hoặc nhấn giữ. Luyện hóa tiêu hao Chân nguyên; nếu không có phản hồi, hãy kiểm tra Chân nguyên và tu vi.', 'Cổ trùng', 30),
('Làm sao để khai khiếu?', 'Dùng **Hi Vọng Cổ**. Có thể tìm thấy thực thể này khi sinh tự nhiên, trong rương di tích, tại Mắt suối Nguyên Tuyền hoặc khi mở Đổ thạch.', 'Tu hành', 40),
('Giải thạch cần cảnh giới nào?', 'Thứ tự yêu cầu: Phổ thông (nhất chuyển) → Xích Thiết (nhất chuyển đỉnh phong) → Bạch Ngân (nhị chuyển đỉnh phong) → Hoàng Kim (tam chuyển đỉnh phong) → Tử Kim (tứ chuyển đỉnh phong). Khí vận càng cao thì cơ hội nhận vật phẩm tốt càng lớn.', 'Vật phẩm', 50),
('Mua bán Cổ trùng bằng cách nào?', 'Mua Cổ từ nhất đến tam chuyển cần **Nguyên Lão Cổ** đặt vào đúng ô chỉ định, không trả trực tiếp bằng Nguyên Thạch. Khi bán cho thương nhân, đặt Cổ hoặc Cổ tài bên trái và Nguyên Lão Cổ bên phải.', 'Giao dịch', 60),
('Tìm thị trấn, di tích và công trình ở đâu?', 'Khu vực có quy tắc sinh mob thường cũng sinh công trình, di tích, dungeon hoặc truyền thừa. Đảo nấm là ngoại lệ đáng chú ý.', 'Thế giới', 70),
('Làm sao biến Cương thi trở lại thành người?', '- Nhân vật nam dùng **Âm Cổ**, nữ dùng **Dương Cổ**; mặc định khi tạo thế giới là nam. Từ ngũ chuyển trở lên, Âm Dương Cổ không còn tác dụng.\n- Mang **Khởi Tử Nhân Cổ / Sinh Cổ** khi không quá ngũ chuyển; nhận sát thương chí mạng sẽ hồi sinh thành người.\n- Sát chiêu **Hoán Nhiên Nhất Tân** cũng có thể giải trạng thái này.', 'Tu hành', 80),
('Vì sao nhấp phải Cổ trùng nhưng không có tác dụng?', '1. Một số Cổ yêu cầu **cùng chuyển với tu vi**.\n2. Độ bền đã giảm nhưng chưa kích hoạt nghĩa là cần dùng thêm lần nữa. Khi thành công thường có âm thanh, tiêu hao Chân nguyên và vào hồi chiêu.\n3. Chân nguyên không đủ hoặc không đúng chuyển.\n4. Save từ phiên bản cũ có thể lỗi và cần tạo thế giới mới.', 'Khắc phục lỗi', 90),
('Dùng Thú lực Hư ảnh và Toàn Lực Dĩ Phó Cổ thế nào?', '- Dùng các Cổ chứa Thú lực Hư ảnh như Tuấn Mã Chi Lực, Thanh Ngưu Lao Lực, Thạch Quy Phụ Lực, Liệt Diễm Hùng Lực, Cuồng Điện Lang Lực hoặc Long Lực Cổ.\n- Toàn Lực Dĩ Phó Cổ phải **cùng chuyển với tu vi**.\n- Gán phím Đánh thường vào chuột trái, nhấn `R` bật chiến đấu và để trống tay chính. Khi đánh, ngồi xổm sinh nhóm Hư ảnh Cuồng Điện Lang/Tuấn Mã/Thanh Ngưu; đứng thường sinh Thạch Quy/Liệt Diễm Hùng/Long lực.', 'Chiến đấu', 100),
('Vì sao không gây được sát thương lên dã thú, Cổ sư hoặc NPC?', 'Hầu hết sinh vật đều có **Armor**, một số còn có mức giáp tối thiểu. Hãy dùng kỹ năng phá giáp như Hoàng Kim Nguyệt Cổ, Phong Thương Cổ, Kim Long Cổ, Huyễn Kiếm Vũ Cổ, Khô Vinh Du hoặc Thu Cổ.', 'Chiến đấu', 110),
('Một số Cổ đặc biệt sử dụng thế nào?', '- **Cốt Nhục Đoàn Viên Cổ**: người cao cầm vòng đỏ, người thấp cầm vòng xanh, đứng sát nhau rồi bấm Ôn dưỡng không khiếu.\n- **Huyết Lô Cổ**: cầm ở tay phụ và giết Cổ sư hoang dã; tứ chuyển cần 100 điểm để nhận +100 Tư chất, ngũ chuyển cần 10 điểm.\n- Hồn phách cần để thuần hóa: Bách Thú 100, Thiên Thú 500, Vạn Thú 1.000, Thú Hoàng 10.000.', 'Cổ trùng', 120)
on conflict do nothing;
