create extension if not exists pg_trgm;

alter table public.catalog_entries
  add column if not exists slug text,
  add column if not exists is_published boolean not null default true,
  add column if not exists published_at timestamptz;

update public.catalog_entries
set slug = source_id
where slug is null;

update public.catalog_entries
set published_at = coalesce(published_at, created_at)
where is_published and published_at is null;

alter table public.catalog_entries
  alter column slug set not null;

create unique index if not exists catalog_entries_kind_slug_key
  on public.catalog_entries(kind, slug);
create index if not exists catalog_entries_public_listing_idx
  on public.catalog_entries(kind, category, name)
  where is_published;

alter table public.catalog_entries
  drop constraint if exists catalog_entries_attributes_array,
  add constraint catalog_entries_attributes_array
    check (jsonb_typeof(attributes) = 'array') not valid,
  drop constraint if exists catalog_entries_details_array,
  add constraint catalog_entries_details_array
    check (jsonb_typeof(details) = 'array') not valid;

alter table public.catalog_entries validate constraint catalog_entries_attributes_array;
alter table public.catalog_entries validate constraint catalog_entries_details_array;

create table if not exists public.catalog_entry_attributes (
  id bigint generated by default as identity primary key,
  entry_id bigint not null references public.catalog_entries(id) on delete cascade,
  label text not null,
  value text not null default '',
  sort_order integer not null default 0,
  unique (entry_id, sort_order)
);

create table if not exists public.catalog_entry_sections (
  id bigint generated by default as identity primary key,
  entry_id bigint not null references public.catalog_entries(id) on delete cascade,
  heading text,
  body text not null,
  sort_order integer not null default 0,
  unique (entry_id, sort_order)
);

create table if not exists public.catalog_media (
  id bigint generated by default as identity primary key,
  entry_id bigint not null references public.catalog_entries(id) on delete cascade,
  media_type text not null default 'image' check (media_type in ('image', 'video', 'audio')),
  path text not null,
  alt_text text not null default '',
  is_primary boolean not null default false,
  sort_order integer not null default 0,
  unique (entry_id, path)
);

create unique index if not exists catalog_media_one_primary_idx
  on public.catalog_media(entry_id)
  where is_primary;

create table if not exists public.recipes (
  id bigint generated by default as identity primary key,
  source_id text not null unique,
  name text not null,
  summary text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.recipe_outputs (
  recipe_id bigint not null references public.recipes(id) on delete cascade,
  entry_id bigint not null references public.catalog_entries(id) on delete cascade,
  is_primary boolean not null default false,
  match_method text not null default 'manual',
  confidence smallint not null default 100 check (confidence between 0 and 100),
  primary key (recipe_id, entry_id)
);

create table if not exists public.recipe_components (
  id bigint generated by default as identity primary key,
  recipe_id bigint not null references public.recipes(id) on delete cascade,
  position integer not null check (position > 0),
  raw_text text not null,
  ingredient_entry_id bigint references public.catalog_entries(id) on delete set null,
  quantity numeric,
  unit text,
  stage_percent smallint check (stage_percent between 0 and 100),
  note text,
  unique (recipe_id, position)
);

create table if not exists public.catalog_entry_relations (
  from_entry_id bigint not null references public.catalog_entries(id) on delete cascade,
  to_entry_id bigint not null references public.catalog_entries(id) on delete cascade,
  relation_type text not null,
  note text,
  sort_order integer not null default 0,
  primary key (from_entry_id, to_entry_id, relation_type),
  check (from_entry_id <> to_entry_id)
);

create table if not exists public.content_import_runs (
  id bigint generated by default as identity primary key,
  source_name text not null,
  source_version text,
  status text not null check (status in ('running', 'succeeded', 'failed')),
  stats jsonb not null default '{}'::jsonb,
  error_message text,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

alter table public.killer_move_slots
  add column if not exists item_entry_id bigint references public.catalog_entries(id) on delete set null;

alter table public.wiki_chapters
  add column if not exists is_published boolean not null default true,
  add column if not exists created_at timestamptz not null default now();

insert into public.catalog_entry_attributes (entry_id, label, value, sort_order)
select
  entry.id,
  attribute.value ->> 0,
  coalesce(attribute.value ->> 1, ''),
  attribute.ordinality::integer - 1
from public.catalog_entries as entry
cross join lateral jsonb_array_elements(entry.attributes) with ordinality as attribute(value, ordinality)
where jsonb_typeof(attribute.value) = 'array'
  and jsonb_array_length(attribute.value) >= 1
on conflict (entry_id, sort_order) do update
set label = excluded.label,
    value = excluded.value;

insert into public.catalog_entry_sections (entry_id, heading, body, sort_order)
select
  entry.id,
  null,
  detail.value #>> '{}',
  detail.ordinality::integer - 1
from public.catalog_entries as entry
cross join lateral jsonb_array_elements(entry.details) with ordinality as detail(value, ordinality)
where jsonb_typeof(detail.value) = 'string'
on conflict (entry_id, sort_order) do update
set body = excluded.body;

insert into public.catalog_media (entry_id, path, alt_text, is_primary, sort_order)
select id, image_path, name, true, 0
from public.catalog_entries
where image_path is not null
on conflict (entry_id, path) do update
set alt_text = excluded.alt_text,
    is_primary = true,
    sort_order = 0;

insert into public.recipes (source_id, name, summary)
select distinct on (source_id) source_id, name, summary
from public.gu_recipes
order by source_id, id
on conflict (source_id) do update
set name = excluded.name,
    summary = excluded.summary;

insert into public.recipe_outputs (recipe_id, entry_id, is_primary, match_method, confidence)
select distinct
  recipe.id,
  legacy.gu_entry_id,
  false,
  case
    when legacy.source_id like entry.source_id || '%' then 'source-id-prefix'
    when entry.source_id like regexp_replace(legacy.source_id, '(?:_?gu)?_?gu_?fang$', '', 'i') || '%' then 'source-id-prefix'
    else 'name-heuristic'
  end,
  case
    when legacy.source_id like entry.source_id || '%' then 100
    when entry.source_id like regexp_replace(legacy.source_id, '(?:_?gu)?_?gu_?fang$', '', 'i') || '%' then 90
    else 50
  end
from public.gu_recipes as legacy
join public.recipes as recipe on recipe.source_id = legacy.source_id
join public.catalog_entries as entry on entry.id = legacy.gu_entry_id
on conflict (recipe_id, entry_id) do update
set match_method = excluded.match_method,
    confidence = excluded.confidence;

with canonical_legacy_recipe as (
  select distinct on (source_id) id as legacy_id, source_id
  from public.gu_recipes
  order by source_id, id
)
insert into public.recipe_components (recipe_id, position, raw_text)
select recipe.id, ingredient.position, ingredient.description
from canonical_legacy_recipe as canonical
join public.recipes as recipe on recipe.source_id = canonical.source_id
join public.recipe_ingredients as ingredient on ingredient.recipe_id = canonical.legacy_id
on conflict (recipe_id, position) do update
set raw_text = excluded.raw_text;

update public.killer_move_slots as slot
set item_entry_id = entry.id
from public.catalog_entries as entry
where slot.item_entry_id is null
  and entry.kind = 'gu'
  and entry.source_id = slot.item_source_id;

create index if not exists catalog_entry_attributes_entry_idx
  on public.catalog_entry_attributes(entry_id, sort_order);
create index if not exists catalog_entry_sections_entry_idx
  on public.catalog_entry_sections(entry_id, sort_order);
create index if not exists catalog_media_entry_idx
  on public.catalog_media(entry_id, sort_order);
create index if not exists recipe_outputs_entry_idx
  on public.recipe_outputs(entry_id, confidence desc);
create index if not exists recipe_components_recipe_idx
  on public.recipe_components(recipe_id, position);
create index if not exists recipe_components_ingredient_idx
  on public.recipe_components(ingredient_entry_id)
  where ingredient_entry_id is not null;
create index if not exists killer_move_slots_item_entry_idx
  on public.killer_move_slots(item_entry_id)
  where item_entry_id is not null;
create index if not exists catalog_entry_relations_to_idx
  on public.catalog_entry_relations(to_entry_id, relation_type);

drop trigger if exists recipes_updated_at on public.recipes;
create trigger recipes_updated_at
before update on public.recipes
for each row execute function public.set_updated_at();

alter table public.catalog_entry_attributes enable row level security;
alter table public.catalog_entry_sections enable row level security;
alter table public.catalog_media enable row level security;
alter table public.recipes enable row level security;
alter table public.recipe_outputs enable row level security;
alter table public.recipe_components enable row level security;
alter table public.catalog_entry_relations enable row level security;
alter table public.content_import_runs enable row level security;

grant select on public.catalog_entry_attributes, public.catalog_entry_sections,
  public.catalog_media, public.recipes, public.recipe_outputs,
  public.recipe_components, public.catalog_entry_relations
to anon, authenticated;

grant all privileges on public.catalog_entry_attributes, public.catalog_entry_sections,
  public.catalog_media, public.recipes, public.recipe_outputs,
  public.recipe_components, public.catalog_entry_relations,
  public.content_import_runs
to service_role;

grant usage, select on all sequences in schema public to service_role;

drop policy if exists "Public catalog is readable" on public.catalog_entries;
create policy "Published catalog is readable"
on public.catalog_entries for select to anon, authenticated
using (is_published);

drop policy if exists "Public wiki is readable" on public.wiki_chapters;
create policy "Published wiki is readable"
on public.wiki_chapters for select to anon, authenticated
using (is_published);

create policy "Published attributes are readable"
on public.catalog_entry_attributes for select to anon, authenticated
using (exists (
  select 1 from public.catalog_entries entry
  where entry.id = catalog_entry_attributes.entry_id and entry.is_published
));

create policy "Published sections are readable"
on public.catalog_entry_sections for select to anon, authenticated
using (exists (
  select 1 from public.catalog_entries entry
  where entry.id = catalog_entry_sections.entry_id and entry.is_published
));

create policy "Published media are readable"
on public.catalog_media for select to anon, authenticated
using (exists (
  select 1 from public.catalog_entries entry
  where entry.id = catalog_media.entry_id and entry.is_published
));

create policy "Published recipes are readable"
on public.recipes for select to anon, authenticated
using (exists (
  select 1
  from public.recipe_outputs output
  join public.catalog_entries entry on entry.id = output.entry_id
  where output.recipe_id = recipes.id and entry.is_published
));

create policy "Published recipe outputs are readable"
on public.recipe_outputs for select to anon, authenticated
using (exists (
  select 1 from public.catalog_entries entry
  where entry.id = recipe_outputs.entry_id and entry.is_published
));

create policy "Published recipe components are readable"
on public.recipe_components for select to anon, authenticated
using (exists (
  select 1
  from public.recipe_outputs output
  join public.catalog_entries entry on entry.id = output.entry_id
  where output.recipe_id = recipe_components.recipe_id and entry.is_published
));

create policy "Published relations are readable"
on public.catalog_entry_relations for select to anon, authenticated
using (
  exists (
    select 1 from public.catalog_entries source
    where source.id = catalog_entry_relations.from_entry_id and source.is_published
  )
  and exists (
    select 1 from public.catalog_entries target
    where target.id = catalog_entry_relations.to_entry_id and target.is_published
  )
);

create or replace function public.search_catalog(
  p_query text default null,
  p_kind text default null,
  p_category text default null,
  p_limit integer default 24,
  p_offset integer default 0
)
returns table (
  id bigint,
  kind text,
  source_id text,
  slug text,
  name text,
  image_path text,
  category text,
  rank text,
  summary text,
  total_count bigint
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    entry.id,
    entry.kind,
    entry.source_id,
    entry.slug,
    entry.name,
    entry.image_path,
    entry.category,
    entry.rank,
    entry.summary,
    count(*) over() as total_count
  from public.catalog_entries as entry
  where entry.is_published
    and (p_kind is null or entry.kind = p_kind)
    and (p_category is null or entry.category = p_category)
    and (
      nullif(trim(p_query), '') is null
      or entry.search_text ilike '%' || trim(p_query) || '%'
      or entry.search_text operator(public.%) trim(p_query)
    )
  order by
    case
      when nullif(trim(p_query), '') is null then 0
      else public.similarity(entry.search_text, trim(p_query))
    end desc,
    entry.name asc
  limit least(greatest(p_limit, 1), 100)
  offset greatest(p_offset, 0);
$$;

grant execute on function public.search_catalog(text, text, text, integer, integer)
to anon, authenticated;

comment on table public.recipes is
  'Canonical Gu recipes. A recipe is stored once and linked to one or more outputs.';
comment on table public.recipe_outputs is
  'Many-to-many recipe-to-catalog links. Low confidence marks heuristic imports requiring review.';
comment on column public.recipe_components.raw_text is
  'Lossless original ingredient line. Parsed quantity, unit and item link are optional enrichments.';
comment on table public.content_import_runs is
  'Private audit log for repeatable catalog imports; service_role only.';
